<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBezVlax\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBezVlax/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBezVlax.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBezVlax\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBezVlax\App_KernelDevDebugContainer([
    'container.build_hash' => 'BezVlax',
    'container.build_id' => 'ad2e854c',
    'container.build_time' => 1651507037,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBezVlax');
